[package]
name = "sss_fontbuild"
description = "Rebuild font files for Lunar: Silver Star Story"
version = "0.1.0"
authors = ["Misty De Meo <mistydemeo@gmail.com>"]

[dependencies]
glob = "0.2.11"
png = "0.9.0"
quicli = "0.2.0"
regex = "0.2"
sega_cmp = "0.2.0"
